before_commands:
    - "composer install --no-dev --prefer-source"

filter:
    excluded_paths:
        - test/*
        - vendor/*

checks:
    php:
        argument_type_checks: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        return_doc_comments: true
        properties_in_camelcaps: true
        custom_coding_standard:
            ruleset_path: phpcs.xml
        avoid_todo_comments: true
        avoid_fixme_comments: true
        line_length:
            max_length: '120'
        function_in_camel_caps: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        phpunit_assertions: true
        simplify_boolean_return: true
        use_self_instead_of_fqcn: true
        parameter_doc_comments: true

tools:
    external_code_coverage:
        timeout: 600
    php_code_coverage:
        enabled: true
    sensiolabs_security_checker: true
