before_commands:
    - "composer install --no-dev --prefer-source"

filter:
    paths: ["src/*"]
    excluded_paths:
        - test/*
        - vendor/*

checks:
    php:
        argument_type_checks: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        return_doc_comments: true
        properties_in_camelcaps: true
        avoid_todo_comments: true
        avoid_fixme_comments: true
        line_length:
            max_length: '120'
        function_in_camel_caps: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: false
        phpunit_assertions: true
        simplify_boolean_return: true
        use_self_instead_of_fqcn: true
        parameter_doc_comments: true
        duplication: false
        avoid_perl_style_comments: true
        newline_at_end_of_file: true

tools:
    external_code_coverage:
        timeout: 1800
