sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7
      env:
        - EXECUTE_CS_CHECK=true
        - DEPLOY_DOCS=true

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover clover.xml

after_success:
  - chmod +x ./docs/deploy.sh
  - ./docs/deploy.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
